# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tqriKbDYYKp16XfPhAPgw_K5S-Fm8H8T
"""

import requests

# Your MyApiFilms API token
API_TOKEN = '4b0d45ae-16ad-436d-9106-073feb9b1d10'

def search_movies_by_keyword(genre_name):
    """Search for movies using a genre name as a keyword."""
    url = "https://www.myapifilms.com/tmdb/searchMovie"
    params = {
        "movieName": genre_name,  # Using genre name as keyword
        "token": API_TOKEN,
        "format": "json"
    }

    response = requests.get(url, params=params)

    print("\n🔍 Full API Response:")
    print(response.text)  # Print raw API response for debugging

    if response.status_code == 200:
        try:
            data = response.json()  # Parse JSON response

            # Extract movies from 'data' key if present
            if "data" in data and "results" in data["data"] and isinstance(data["data"]["results"], list):
                return data["data"]["results"]  # Return list of movies
            else:
                print("❌ No movies found in API response.")
                return None
        except Exception as e:
            print(f"❌ Error parsing JSON: {e}")
            return None
    else:
        print(f"❌ Error: Failed to retrieve data. Status Code: {response.status_code}")
        return None

def main():
    genre_name = input("🎬 Enter a genre name (e.g., Action, Comedy, Horror): ")

    movies = search_movies_by_keyword(genre_name)

    if movies:
        print("\n🎥 Movies related to:", genre_name.capitalize(), "\n")
        for movie in movies[:10]:  # Limit to 10 movies for better readability
            print(f"⭐ Title: {movie.get('title', 'N/A')}")
            print(f"📅 Release Year: {movie.get('release_date', 'N/A')}")
            print(f"🎭 Rating: {movie.get('vote_average', 'N/A')}")
            print(f"📝 Overview: {movie.get('overview', 'N/A')}\n")
    else:
        print("❌ No movies found for this genre.")

# Run the function in Colab
main()